"""Bind a template's auto-extracted ``field_id``s to human-authored names.

``placeholder_map.json`` is generated by ``core.templates.hwpx_content_separator``
and its ``field_id``s (``content_01``, ``body_bullet_03``) are *positional*: the
separator numbers them in document order, so adding a paragraph to the reference
form shifts every later number in that category. A content file keyed by
``field_id`` alone would still load after such a shift and silently fill the wrong
paragraphs.

``alias_map.json`` is the human half of that contract. A person writes it once,
next to the approval decision, and it survives re-extraction because the
separator never writes this file.

Honesty:
- A template without ``alias_map.json`` resolves to nothing; the renderer keeps
  its current ``field_id``-only behavior.
- An alias pointing at a ``field_id`` the placeholder map does not contain is an
  error, not a skipped entry — that is exactly the shift described above.
- Content keys matching neither an alias nor a ``field_id`` are reported as
  unknown, never dropped silently.
"""
from __future__ import annotations

import json
import re
from collections.abc import Mapping
from dataclasses import dataclass, field
from pathlib import Path
from typing import TypeAlias

JsonScalar: TypeAlias = str | int | float | bool | None
JsonValue: TypeAlias = JsonScalar | list["JsonValue"] | dict[str, "JsonValue"]

ALIAS_MAP_NAME = "alias_map.json"
_SENTENCE_TERMINAL_RE = re.compile(r"[.!?]")


class AliasMapError(ValueError):
    """Raised when an alias map is invalid or conflicts with the content."""


@dataclass(frozen=True, slots=True)
class RepeatBlock:
    anchor: str
    levels: dict[int, tuple[str, str]]
    numbered_level: int | None = None
    item_separator_levels: tuple[int, ...] = ()
    section_transition: tuple[int, int] | None = None


@dataclass(frozen=True, slots=True)
class TextRule:
    single_paragraph: bool
    single_sentence: bool
    forbidden_suffix: str | None = None
    prefix: str = ""
    suffix: str = ""

    def format_value(self, alias: str, value: JsonValue) -> str:
        if not isinstance(value, str) or not value.strip():
            raise AliasMapError(
                f"text field {alias!r} must be a non-empty string"
            )
        if self.single_paragraph and ("\r" in value or "\n" in value):
            raise AliasMapError(
                f"text field {alias!r} must be a single paragraph"
            )
        stripped = value.strip()
        if self.single_sentence:
            terminal_marks = _SENTENCE_TERMINAL_RE.findall(stripped)
            if len(terminal_marks) != 1 or stripped[-1] not in ".!?":
                raise AliasMapError(
                    f"text field {alias!r} must be one sentence "
                    "ending with one terminal mark"
                )
        if (
            self.forbidden_suffix is not None
            and stripped.endswith(self.forbidden_suffix)
        ):
            raise AliasMapError(
                f"text field {alias!r} must not include suffix "
                f"{self.forbidden_suffix!r}"
            )
        return f"{self.prefix}{value}{self.suffix}"


@dataclass(frozen=True, slots=True)
class FitConstraint:
    max_lines: int


@dataclass(frozen=True, slots=True)
class FieldMetadataSource:
    alias: str
    suffix: str = ""


@dataclass(frozen=True, slots=True)
class BlockMetadataSource:
    block: str
    level: int


@dataclass(frozen=True, slots=True)
class RequestedAtMetadataSource:
    pass


MetadataSource: TypeAlias = (
    FieldMetadataSource | BlockMetadataSource | RequestedAtMetadataSource
)


@dataclass(frozen=True, slots=True)
class MetadataContract:
    title: FieldMetadataSource
    report_date: FieldMetadataSource | RequestedAtMetadataSource
    description: FieldMetadataSource
    subject: FieldMetadataSource | BlockMetadataSource
    subject_separator: str
    keywords: tuple[FieldMetadataSource | BlockMetadataSource, ...]
    keyword_separator: str


@dataclass(frozen=True, slots=True)
class ChoiceRule:
    options: tuple[str, ...]
    checked_prefix: str
    unchecked_prefix: str
    separator: str

    def format_value(self, alias: str, value: JsonValue) -> str:
        if not isinstance(value, str):
            raise AliasMapError(f"choice field {alias!r} must be a string")
        if value not in self.options:
            raise AliasMapError(
                f"choice field {alias!r} has unknown option {value!r}"
            )

        # 각 prefix에는 체크 기호와 뒤 공백까지 들어 있으므로 선택지 이름만 붙인다.
        return self.separator.join(
            (
                self.checked_prefix
                if option == value
                else self.unchecked_prefix
            )
            + option
            for option in self.options
        )


@dataclass(frozen=True, slots=True)
class AliasMap:
    """A validated ``alias path -> field_id`` binding for one template."""

    template_id: str | None
    aliases: dict[str, str]
    blocks: dict[str, RepeatBlock] = field(default_factory=dict)
    choices: dict[str, ChoiceRule] = field(default_factory=dict)
    text_rules: dict[str, TextRule] = field(default_factory=dict)
    fit_constraints: dict[str, FitConstraint] = field(default_factory=dict)
    metadata: MetadataContract | None = None
    title_field_id: str | None = None

    @property
    def referenced_field_ids(self) -> frozenset[str]:
        """Every ``field_id`` this alias map binds human input to.

        The alias map is the only place that knows which of its structures hold
        field IDs, so identity checks ask it rather than re-reading its JSON.
        """
        referenced = set(self.aliases.values()) | set(self.fit_constraints)
        for block in self.blocks.values():
            referenced.add(block.anchor)
            referenced.update(field_id for field_id, _ in block.levels.values())
        if self.title_field_id is not None:
            referenced.add(self.title_field_id)
        return frozenset(referenced)

    def flatten_content(
        self,
        content: Mapping[str, JsonValue],
        field_ids: frozenset[str],
    ) -> dict[str, JsonValue]:
        """Key ``content`` by alias path once, before any rule is applied.

        This is the only pass over the human-authored mapping: every later
        reader (render values, document metadata) works from the result.
        """
        flattened: dict[str, JsonValue] = {}
        for path, value in content.items():
            block = self.blocks.get(path)
            if path in field_ids:
                flattened[path] = value
            elif block is not None:
                _validate_repeat_items(path, value, block)
                flattened[block.anchor] = value
            else:
                flattened.update(flatten({path: value}))
        return flattened

    def resolve_flattened(
        self,
        flattened: Mapping[str, JsonValue],
        field_ids: frozenset[str],
    ) -> tuple[dict[str, JsonValue], list[str]]:
        """Apply the choice and text rules and key the result by ``field_id``."""
        resolved: dict[str, JsonValue] = {}
        source_path: dict[str, str] = {}
        unknown: list[str] = []
        alias_by_field = {
            field_id: alias for alias, field_id in self.aliases.items()
        }
        for path, value in flattened.items():
            # 선택 규칙은 사람용 이름으로 연결되므로 field_id로 바꾸기 전에 완성한다.
            choice = self.choices.get(path)
            if choice is not None:
                value = choice.format_value(path, value)
            # 텍스트 규칙은 사람용 이름에 연결되므로 field_id로 바꾸기 전에 적용한다.
            text_alias = alias_by_field.get(path, path)
            text_rule = self.text_rules.get(text_alias)
            if text_rule is not None:
                value = text_rule.format_value(text_alias, value)

            field_id = self.aliases.get(path)
            if field_id is None:
                if path not in field_ids:
                    unknown.append(path)
                    continue
                field_id = path
            if field_id in resolved and resolved[field_id] != value:
                raise AliasMapError(
                    f"conflicting values for field {field_id!r}: "
                    f"{source_path[field_id]!r} and {path!r}"
                )
            resolved[field_id] = value
            source_path[field_id] = path
        return resolved, sorted(unknown)

    def resolve(
        self,
        content: Mapping[str, JsonValue],
        field_ids: frozenset[str],
    ) -> tuple[dict[str, JsonValue], list[str]]:
        """Flatten ``content`` and key it by ``field_id``.

        Returns ``(resolved, unknown_keys)``. Keys that are already a valid
        ``field_id`` pass through unchanged, so resolving a resolved mapping is a
        no-op and the renderer may call this more than once.
        """
        return self.resolve_flattened(
            self.flatten_content(content, field_ids),
            field_ids,
        )


def flatten(content: Mapping[str, JsonValue]) -> dict[str, JsonValue]:
    """Flatten nested objects and arrays into dotted / indexed alias paths.

    ``{"담당": {"국": "x"}}``   -> ``{"담당.국": "x"}``
    ``{"부제": ["a", "b"]}``    -> ``{"부제[0]": "a", "부제[1]": "b"}``

    Scalars keep their key. Empty objects and arrays contribute no path, so a
    field left out of the content stays missing rather than becoming an empty
    string.
    """
    flat: dict[str, JsonValue] = {}

    def walk(path: str, value: JsonValue) -> None:
        if isinstance(value, dict):
            for key, item in value.items():
                walk(f"{path}.{key}" if path else str(key), item)
        elif isinstance(value, list):
            for index, item in enumerate(value):
                walk(f"{path}[{index}]", item)
        else:
            flat[path] = value

    for key, value in content.items():
        walk(str(key), value)
    return flat


def _validate_repeat_items(name: str, value: JsonValue, block: RepeatBlock) -> None:
    if not isinstance(value, list):
        raise AliasMapError(f"repeat block {name!r} must be an array")
    for index, item in enumerate(value):
        if (
            not isinstance(item, list)
            or len(item) != 2
            or not isinstance(item[0], int)
            or isinstance(item[0], bool)
            or not isinstance(item[1], str)
        ):
            raise AliasMapError(
                f"repeat block {name!r}[{index}] must be [level, text]"
            )
        if item[0] not in block.levels:
            raise AliasMapError(
                f"repeat block {name!r}[{index}] has unknown level {item[0]!r}"
            )


def _parse_choice_rule(
    path: Path,
    alias: str,
    raw: JsonValue,
) -> ChoiceRule:
    context = f"{path}: choice {alias!r}"

    if not isinstance(raw, dict):
        raise AliasMapError(f"{context} must be an object")

    options_raw = raw.get("options")
    if not isinstance(options_raw, list) or not options_raw:
        raise AliasMapError(f"{context} requires options")

    options: list[str] = []
    for option in options_raw:
        if not isinstance(option, str) or not option:
            raise AliasMapError(
                f"{context} options must be non-empty strings"
            )
        options.append(option)

    if len(options) != len(set(options)):
        raise AliasMapError(f"{context} has duplicate options")

    def read_string(name: str, *, allow_empty: bool = False) -> str:
        value = raw.get(name)
        if not isinstance(value, str) or (not allow_empty and not value):
            raise AliasMapError(f"{context} requires string {name!r}")
        return value

    checked_prefix = read_string("checked_prefix")
    unchecked_prefix = read_string("unchecked_prefix")
    if checked_prefix == unchecked_prefix:
        raise AliasMapError(
            f"{context} requires different checked and unchecked prefixes"
        )

    return ChoiceRule(
        options=tuple(options),
        checked_prefix=checked_prefix,
        unchecked_prefix=unchecked_prefix,
        separator=read_string("separator", allow_empty=True),
    )


def _parse_metadata_contract(
    path: Path,
    raw: JsonValue,
    aliases: Mapping[str, str],
    blocks: Mapping[str, RepeatBlock],
    title_alias: str | None,
) -> MetadataContract:
    if not isinstance(raw, dict):
        raise AliasMapError(f"{path}: metadata must be an object")
    required = {"report_date", "description", "subject", "keywords"}
    missing = sorted(required - raw.keys())
    if missing:
        raise AliasMapError(f"{path}: metadata requires {missing}")

    def read_field(context: str, value: JsonValue) -> FieldMetadataSource:
        if not isinstance(value, dict):
            raise AliasMapError(
                f"{path}: metadata {context} must be an object"
            )
        alias = value.get("field")
        if not isinstance(alias, str) or alias not in aliases:
            raise AliasMapError(
                f"{path}: metadata {context} references unknown field "
                f"{alias!r}"
            )
        suffix = value.get("suffix", "")
        if not isinstance(suffix, str):
            raise AliasMapError(
                f"{path}: metadata {context} suffix must be a string"
            )
        return FieldMetadataSource(alias=alias, suffix=suffix)

    def read_block(context: str, value: JsonValue) -> BlockMetadataSource:
        if not isinstance(value, dict):
            raise AliasMapError(
                f"{path}: metadata {context} must be an object"
            )
        name = value.get("block")
        if not isinstance(name, str) or name not in blocks:
            raise AliasMapError(
                f"{path}: metadata {context} references unknown block "
                f"{name!r}"
            )
        level = value.get("level")
        if (
            not isinstance(level, int)
            or isinstance(level, bool)
            or level not in blocks[name].levels
        ):
            raise AliasMapError(
                f"{path}: metadata {context} references unknown level "
                f"{level!r}"
            )
        return BlockMetadataSource(block=name, level=level)

    def read_source(
        context: str,
        value: JsonValue,
        *,
        allow_requested_at: bool = False,
    ) -> MetadataSource:
        if not isinstance(value, dict):
            raise AliasMapError(f"{path}: metadata {context} must be an object")
        if "field" in value:
            return read_field(context, value)
        if "block" in value:
            return read_block(context, value)
        if allow_requested_at and value.get("context") == "requested_at":
            return RequestedAtMetadataSource()
        raise AliasMapError(
            f"{path}: metadata {context} requires field, block, or requested_at"
        )

    title_raw = raw.get("title")
    if title_raw is None:
        if title_alias is None:
            raise AliasMapError(f"{path}: metadata requires title")
        title = FieldMetadataSource(alias=title_alias)
    else:
        title = read_field("title", title_raw)

    report_date = read_source(
        "report_date",
        raw["report_date"],
        allow_requested_at=True,
    )
    if isinstance(report_date, BlockMetadataSource):
        raise AliasMapError(f"{path}: metadata report_date cannot use a block")
    description = read_field("description", raw["description"])

    subject_raw = raw["subject"]
    if not isinstance(subject_raw, dict):
        raise AliasMapError(f"{path}: metadata subject must be an object")
    subject_separator = subject_raw.get("separator")
    if not isinstance(subject_separator, str):
        raise AliasMapError(
            f"{path}: metadata subject separator must be a string"
        )
    subject = read_source("subject", subject_raw)
    if isinstance(subject, RequestedAtMetadataSource):
        raise AliasMapError(f"{path}: metadata subject cannot use requested_at")

    keywords_raw = raw["keywords"]
    if not isinstance(keywords_raw, dict):
        raise AliasMapError(f"{path}: metadata keywords must be an object")
    keywords_separator = keywords_raw.get("separator")
    sources_raw = keywords_raw.get("sources")
    if not isinstance(keywords_separator, str):
        raise AliasMapError(
            f"{path}: metadata keywords separator must be a string"
        )
    if not isinstance(sources_raw, list) or not sources_raw:
        raise AliasMapError(f"{path}: metadata keywords requires sources")
    keywords: list[FieldMetadataSource | BlockMetadataSource] = []
    for index, source_raw in enumerate(sources_raw):
        source = read_source(f"keywords.sources[{index}]", source_raw)
        if isinstance(source, RequestedAtMetadataSource):
            raise AliasMapError(
                f"{path}: metadata keywords cannot use requested_at"
            )
        keywords.append(source)
    return MetadataContract(
        title=title,
        report_date=report_date,
        description=description,
        subject=subject,
        subject_separator=subject_separator,
        keywords=tuple(keywords),
        keyword_separator=keywords_separator,
    )


def load_alias_map(
    template_dir: Path | str,
    *,
    field_ids: frozenset[str],
    template_id: str | None = None,
) -> AliasMap | None:
    """Load and validate ``<template_dir>/alias_map.json``; ``None`` if absent."""
    path = Path(template_dir) / ALIAS_MAP_NAME
    if not path.is_file():
        return None

    raw: JsonValue = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(raw, dict):
        raise AliasMapError(f"{path}: root must be an object")

    declared = raw.get("template_id")
    if declared is not None and not isinstance(declared, str):
        raise AliasMapError(f"{path}: template_id must be a string")
    if declared is not None and template_id is not None and declared != template_id:
        raise AliasMapError(
            f"{path}: template_id {declared!r} does not match the "
            f"placeholder map's {template_id!r}"
        )

    alias_key = "fields" if "fields" in raw else "aliases"
    aliases = raw.get(alias_key)
    if not isinstance(aliases, dict):
        raise AliasMapError(f"{path}: {alias_key} must be an object")

    bound: dict[str, str] = {}
    claimed: dict[str, str] = {}
    for alias, field_id in aliases.items():
        if not isinstance(field_id, str) or not field_id:
            raise AliasMapError(f"{path}: alias {alias!r} must map to a field_id string")
        if field_id not in field_ids:
            raise AliasMapError(
                f"{path}: alias {alias!r} points at unknown field_id {field_id!r} "
                "(re-extraction may have renumbered the placeholder map)"
            )
        if field_id in claimed:
            raise AliasMapError(
                f"{path}: field_id {field_id!r} is claimed by both "
                f"{claimed[field_id]!r} and {alias!r}"
            )
        bound[str(alias)] = field_id
        claimed[field_id] = str(alias)

    # 문서 속성 제목으로 쓸 필드. 선언이 없으면 제목은 원본 그대로 둔다.
    title_alias = raw.get("title_field")
    if title_alias is not None and (
        not isinstance(title_alias, str) or title_alias not in bound
    ):
        raise AliasMapError(
            f"{path}: title_field {title_alias!r} is not one of {alias_key}"
        )

    choices_raw = raw.get("choices", {})
    if not isinstance(choices_raw, dict):
        raise AliasMapError(f"{path}: choices must be an object")
    choices: dict[str, ChoiceRule] = {}
    for alias, choice_raw in choices_raw.items():
        if alias not in bound:
            raise AliasMapError(
                f"{path}: choice {alias!r} does not exist in fields"
            )
        choices[alias] = _parse_choice_rule(path, alias, choice_raw)

    text_rules_raw = raw.get("text_rules", {})
    if not isinstance(text_rules_raw, dict):
        raise AliasMapError(f"{path}: text_rules must be an object")
    text_rules: dict[str, TextRule] = {}
    for alias, rule_raw in text_rules_raw.items():
        if alias not in bound:
            raise AliasMapError(
                f"{path}: text rule {alias!r} does not exist in fields"
            )
        if not isinstance(rule_raw, dict):
            raise AliasMapError(
                f"{path}: text rule {alias!r} must be an object"
            )
        single_paragraph = rule_raw.get("single_paragraph")
        if not isinstance(single_paragraph, bool):
            raise AliasMapError(
                f"{path}: text rule {alias!r} requires bool 'single_paragraph'"
            )
        single_sentence = rule_raw.get("single_sentence", False)
        if not isinstance(single_sentence, bool):
            raise AliasMapError(
                f"{path}: text rule {alias!r} requires bool 'single_sentence'"
            )
        forbidden_suffix = rule_raw.get("forbidden_suffix")
        if forbidden_suffix is not None and (
            not isinstance(forbidden_suffix, str) or not forbidden_suffix
        ):
            raise AliasMapError(
                f"{path}: text rule {alias!r} forbidden_suffix "
                "must be a non-empty string"
            )
        prefix = rule_raw.get("prefix", "")
        suffix = rule_raw.get("suffix", "")
        if not isinstance(prefix, str) or not isinstance(suffix, str):
            raise AliasMapError(
                f"{path}: text rule {alias!r} prefix and suffix must be strings"
            )
        text_rules[alias] = TextRule(
            single_paragraph=single_paragraph,
            single_sentence=single_sentence,
            forbidden_suffix=forbidden_suffix,
            prefix=prefix,
            suffix=suffix,
        )

    fit_constraints_raw = raw.get("fit_constraints", {})
    if not isinstance(fit_constraints_raw, dict):
        raise AliasMapError(f"{path}: fit_constraints must be an object")
    fit_constraints: dict[str, FitConstraint] = {}
    for field_id, constraint_raw in fit_constraints_raw.items():
        if field_id not in field_ids:
            raise AliasMapError(
                f"{path}: fit constraint points at unknown field_id "
                f"{field_id!r}"
            )
        if not isinstance(constraint_raw, dict):
            raise AliasMapError(
                f"{path}: fit constraint {field_id!r} must be an object"
            )
        max_lines = constraint_raw.get("max_lines")
        if (
            not isinstance(max_lines, int)
            or isinstance(max_lines, bool)
            or max_lines != 1
        ):
            raise AliasMapError(
                f"{path}: fit constraint {field_id!r} requires max_lines=1"
            )
        fit_constraints[field_id] = FitConstraint(max_lines=max_lines)

    blocks_raw = raw.get("blocks", {})
    if not isinstance(blocks_raw, dict):
        raise AliasMapError(f"{path}: blocks must be an object")
    blocks: dict[str, RepeatBlock] = {}
    for name, block_raw in blocks_raw.items():
        if not isinstance(block_raw, dict):
            raise AliasMapError(f"{path}: block {name!r} must be an object")
        if block_raw.get("repeat") is not True:
            raise AliasMapError(f"{path}: block {name!r} requires repeat=true")
        if block_raw.get("table_scope") is not False:
            raise AliasMapError(f"{path}: block {name!r} requires table_scope=false")
        anchor = block_raw.get("anchor")
        levels_raw = block_raw.get("levels")
        if not isinstance(anchor, str) or anchor not in field_ids:
            raise AliasMapError(f"{path}: block {name!r} has an unknown anchor")
        if not isinstance(levels_raw, dict) or not levels_raw:
            raise AliasMapError(f"{path}: block {name!r} requires levels")
        levels: dict[int, tuple[str, str]] = {}
        for level_text, level_raw in levels_raw.items():
            if not isinstance(level_text, str) or not level_text.isdigit():
                raise AliasMapError(f"{path}: block {name!r} has an invalid level")
            if not isinstance(level_raw, dict):
                raise AliasMapError(
                    f"{path}: block {name!r} level {level_text!r} must be an object"
                )
            field_id = level_raw.get("field")
            prefix = level_raw.get("prefix")
            if not isinstance(field_id, str) or field_id not in field_ids:
                raise AliasMapError(
                    f"{path}: block {name!r} level {level_text!r} has an unknown field"
                )
            if not isinstance(prefix, str):
                raise AliasMapError(
                    f"{path}: block {name!r} level {level_text!r} requires a prefix"
                )
            levels[int(level_text)] = (field_id, prefix)
        numbered_level = block_raw.get("numbered_level")
        if (
            numbered_level is not None
            and (
                not isinstance(numbered_level, int)
                or isinstance(numbered_level, bool)
                or numbered_level not in levels
            )
        ):
            raise AliasMapError(
                f"{path}: block {name!r} has an unknown numbered_level"
            )
        item_separator_levels_raw = block_raw.get("item_separator_levels", [])
        if not isinstance(item_separator_levels_raw, list):
            raise AliasMapError(
                f"{path}: block {name!r} item_separator_levels must be an array"
            )
        item_separator_levels: list[int] = []
        for separator_level in item_separator_levels_raw:
            if (
                not isinstance(separator_level, int)
                or isinstance(separator_level, bool)
                or separator_level not in levels
            ):
                raise AliasMapError(
                    f"{path}: block {name!r} has an unknown "
                    "item_separator_levels value"
                )
            item_separator_levels.append(separator_level)
        if len(item_separator_levels) != len(set(item_separator_levels)):
            raise AliasMapError(
                f"{path}: block {name!r} has duplicate item_separator_levels"
            )

        section_transition_raw = block_raw.get("section_transition")
        section_transition: tuple[int, int] | None = None
        if section_transition_raw is not None:
            if not isinstance(section_transition_raw, dict):
                raise AliasMapError(
                    f"{path}: block {name!r} section_transition must be an object"
                )
            transition_levels: list[int] = []
            for key in (
                "to_level",
                "separator_source_level",
            ):
                transition_level = section_transition_raw.get(key)
                if (
                    not isinstance(transition_level, int)
                    or isinstance(transition_level, bool)
                    or transition_level not in levels
                ):
                    raise AliasMapError(
                        f"{path}: block {name!r} section_transition "
                        f"has an unknown {key}"
                    )
                transition_levels.append(transition_level)
            section_transition = (
                transition_levels[0],
                transition_levels[1],
            )
        blocks[str(name)] = RepeatBlock(
            anchor=anchor,
            levels=levels,
            numbered_level=numbered_level,
            item_separator_levels=tuple(item_separator_levels),
            section_transition=section_transition,
        )

    metadata_raw = raw.get("metadata")
    metadata = (
        _parse_metadata_contract(path, metadata_raw, bound, blocks, title_alias)
        if metadata_raw is not None
        else None
    )
    if declared == "fss_director_report" and metadata is None:
        raise AliasMapError(
            f"{path}: fss_director_report requires metadata"
        )

    return AliasMap(
        template_id=declared,
        aliases=bound,
        blocks=blocks,
        choices=choices,
        text_rules=text_rules,
        fit_constraints=fit_constraints,
        metadata=metadata,
        title_field_id=bound[title_alias] if title_alias is not None else None,
    )
